import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import HamburgerMenu from "./HamburgerMenu";
import Link from "next/link";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Header() {
  return (
    <header
      style={{
        position: 'sticky',
        top: 0,
        left: 0,
        width: '100%',
        zIndex: 200,
        background: '#fff',
        borderBottom: '1px solid #ececec',
        boxShadow: '0 2px 8px rgba(44,62,80,0.06)',
        display: 'flex',
        alignItems: 'center',
        padding: '0.5rem 2rem',
        minHeight: 64,
        justifyContent: 'space-between',
      }}
    >
      <div style={{ display: 'flex', alignItems: 'center', gap: 16 }}>
        <Link href="/">
          <Image src="/globe.svg" alt="Popup-Pro Logo" width={38} height={38} style={{ display: 'block' }} />
        </Link>
      </div>
      <div style={{ display: 'flex', alignItems: 'center', gap: 16, marginRight: 20 }}>
        <input
          type="text"
          placeholder="Search..."
          style={{ padding: '0.5rem 1rem', border: '1px solid #ececec', borderRadius: 8, fontSize: '1rem', minWidth: 180, marginRight: 0, marginLeft: 0 }}
        />
        <Link href="/login" style={{ color: '#E4861B', background: 'none', border: 'none', borderRadius: 8, padding: '0.5rem 1.2rem', fontWeight: 600, fontSize: '1rem', textDecoration: 'none', marginLeft: 16, marginRight: 0, cursor: 'pointer' }}>Login / Signup</Link>
        <div style={{ marginRight: 0 }}>
          <HamburgerMenu />
        </div>
      </div>
    </header>
  );
}

function Footer() {
  return (
    <footer style={{ background: '#fff', borderTop: '1px solid #ececec', marginTop: 40, padding: '2.5rem 2rem 1.2rem 2rem', width: '100%' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', flexWrap: 'wrap', maxWidth: 1200, margin: '0 auto' }}>
        {/* Left: Logo and Description */}
        <div style={{ flex: '1 1 220px', minWidth: 220 }}>
          <Image src="/globe.svg" alt="Popup-Pro Logo" width={38} height={38} style={{ display: 'block', marginBottom: 12 }} />
          <div style={{ color: '#23243a', fontSize: '1.05rem', maxWidth: 260, lineHeight: 1.6 }}>
            Popup-Pro connects you with South Africa&apos;s best local vendors, entertainers, and event services. Discover, compare, and book everything you need to bring your celebration to life!
          </div>
        </div>
        {/* Center: Navigation Links */}
        <div style={{ flex: '1 1 180px', minWidth: 180, display: 'flex', flexDirection: 'column', alignItems: 'flex-start', gap: 8, marginRight: 50 }}>
          <nav style={{ display: 'flex', flexDirection: 'column', gap: 8, alignItems: 'flex-start' }}>
            <Link href="/" style={{ color: '#E4861B', fontWeight: 600, fontVariationSettings: '"wght" 550', textDecoration: 'none', fontSize: '1.05rem' }}>Home</Link>
            <Link href="/vendors" style={{ color: '#E4861B', fontWeight: 600, fontVariationSettings: '"wght" 550', textDecoration: 'none', fontSize: '1.05rem' }}>Vendors</Link>
            <Link href="/login" style={{ color: '#E4861B', fontWeight: 600, fontVariationSettings: '"wght" 550', textDecoration: 'none', fontSize: '1.05rem' }}>Login</Link>
            <Link href="/signup" style={{ color: '#E4861B', fontWeight: 600, fontVariationSettings: '"wght" 550', textDecoration: 'none', fontSize: '1.05rem' }}>Signup</Link>
          </nav>
        </div>
        {/* Right: Email Subscribe */}
        <div style={{ flex: '1 1 260px', minWidth: 220, display: 'flex', flexDirection: 'column', alignItems: 'flex-start', marginRight: 20 }}>
          <label htmlFor="footer-email" style={{ color: '#23243a', fontWeight: 600, marginBottom: 8, fontSize: '1.05rem' }}>Subscribe for updates</label>
          <div style={{ width: 220 }}>
            <input id="footer-email" type="email" placeholder="Your email address" style={{ padding: '0.7rem 1rem', border: '1px solid #ececec', borderRadius: 8, fontSize: '1rem', width: '100%', marginBottom: 8 }} />
            <button style={{ background: 'linear-gradient(90deg, #E4861B 0%, #eab676 100%)', color: '#fff', border: 'none', borderRadius: 8, fontWeight: 700, fontSize: '1rem', padding: '0.7rem 1.2rem', cursor: 'pointer', width: '100%' }}>Subscribe</button>
          </div>
        </div>
      </div>
      {/* Bottom Center: Terms | Privacy */}
      <div style={{ textAlign: 'center', marginTop: 32, color: '#23243a', fontSize: '1rem', fontWeight: 500 }}>
        <Link href="/terms" style={{ color: '#23243a', textDecoration: 'underline', marginRight: 16 }}>Terms</Link>
        |
        <Link href="/privacy" style={{ color: '#23243a', textDecoration: 'underline', marginLeft: 16 }}>Privacy</Link>
      </div>
    </footer>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
